-- MySQL Script generated by MySQL Workbench
-- Sun Jan  5 17:10:09 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema airport
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `airport` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `airport` DEFAULT CHARACTER SET utf8 ;
USE `airport` ;

-- -----------------------------------------------------
-- Table `airport`.`Passengers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airport`.`Passengers` (
  `passenger_id` INT NOT NULL AUTO_INCREMENT,
  `passenger_first_name` VARCHAR(25) NOT NULL,
  `passenger_second_name` VARCHAR(25) NOT NULL,
  `passenger_last_name` VARCHAR(25) NOT NULL,
  `gender` ENUM('Male', 'Female', 'Other') NOT NULL,
  `date_of_birth` DATE NOT NULL,
  PRIMARY KEY (`passenger_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airport`.`DocumentTypes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airport`.`DocumentTypes` (
  `document_type_id` INT NOT NULL AUTO_INCREMENT,
  `document_type` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`document_type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airport`.`Countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airport`.`Countries` (
  `country_code` VARCHAR(3) NOT NULL,
  `country_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`country_code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airport`.`Documents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airport`.`Documents` (
  `document_id` INT NOT NULL AUTO_INCREMENT,
  `document_type_id` INT NOT NULL,
  `passenger_id` INT NOT NULL,
  `issue_date` DATE NOT NULL,
  `expiration_date` DATE NOT NULL,
  `country_code` VARCHAR(3) NOT NULL,
  `document_number` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`document_id`),
  INDEX `fk_Documents_Passenger1_idx` (`passenger_id` ASC) VISIBLE,
  INDEX `fk_Documents_DocumentType1_idx` (`document_type_id` ASC) VISIBLE,
  INDEX `fk_Documents_Countries1_idx` (`country_code` ASC) VISIBLE,
  CONSTRAINT `fk_Documents_Passenger1`
    FOREIGN KEY (`passenger_id`)
    REFERENCES `mydb`.`Passengers` (`passenger_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Documents_DocumentType1`
    FOREIGN KEY (`document_type_id`)
    REFERENCES `mydb`.`DocumentTypes` (`document_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Documents_Countries1`
    FOREIGN KEY (`country_code`)
    REFERENCES `mydb`.`Countries` (`country_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airport`.`AirplaneTypes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airport`.`AirplaneTypes` (
  `ariplane_type_id` INT NOT NULL AUTO_INCREMENT,
  `model_type` VARCHAR(30) NOT NULL,
  `manufacture` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`ariplane_type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AirplaneCompanies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airport`.`AirplaneCompanies` (
  `company_iata` CHAR(2) NOT NULL,
  `company_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`company_iata`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airport`.`Airplanes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airport`.`Airplanes` (
  `airplane_registration_number` VARCHAR(20) NOT NULL,
  `airplane_type_id` INT NOT NULL,
  `company_iata` CHAR(2) NOT NULL,
  PRIMARY KEY (`airplane_registration_number`),
  INDEX `fk_Airplanes_AirplaneTypes1_idx` (`airplane_type_id` ASC) VISIBLE,
  INDEX `fk_Airplanes_AirplaneCompanies1_idx` (`company_iata` ASC) VISIBLE,
  CONSTRAINT `fk_Airplanes_AirplaneTypes1`
    FOREIGN KEY (`airplane_type_id`)
    REFERENCES `mydb`.`AirplaneTypes` (`ariplane_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Airplanes_AirplaneCompanies1`
    FOREIGN KEY (`company_iata`)
    REFERENCES `mydb`.`AirplaneCompanies` (`company_iata`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airport`.`floors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airport`.`floors` (
  `floor_id` INT NOT NULL AUTO_INCREMENT,
  `airplane_type_id` INT NOT NULL,
  `floor_number` INT NULL DEFAULT 1,
  PRIMARY KEY (`floor_id`),
  INDEX `fk_floors_AirplaneTypes1_idx` (`airplane_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_floors_AirplaneTypes1`
    FOREIGN KEY (`airplane_type_id`)
    REFERENCES `mydb`.`AirplaneTypes` (`ariplane_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airport`.`SeatsClass`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airport`.`SeatsClass` (
  `seat_class_id` INT NOT NULL AUTO_INCREMENT,
  `seat_class_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`seat_class_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airport`.`Seats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airport`.`Seats` (
  `seat_id` INT NOT NULL AUTO_INCREMENT,
  `airplane_registration_number` VARCHAR(20) NOT NULL,
  `row` INT NOT NULL,
  `column` VARCHAR(1) NOT NULL,
  `is_avaivable` TINYINT NULL DEFAULT 1,
  `seat_class_id` INT NOT NULL,
  PRIMARY KEY (`seat_id`),
  INDEX `fk_Seats_Airplanes1_idx` (`airplane_registration_number` ASC) VISIBLE,
  INDEX `fk_Seats_SeatsClass1_idx` (`seat_class_id` ASC) VISIBLE,
  CONSTRAINT `fk_Seats_Airplanes1`
    FOREIGN KEY (`airplane_registration_number`)
    REFERENCES `mydb`.`Airplanes` (`airplane_registration_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Seats_SeatsClass1`
    FOREIGN KEY (`seat_class_id`)
    REFERENCES `mydb`.`SeatsClass` (`seat_class_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airport`.`Airports`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airport`.`Airports` (
  `airport_iata` CHAR(3) NOT NULL,
  `airport_name` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `country_code` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`airport_iata`),
  INDEX `fk_Airports_Countries1_idx` (`country_code` ASC) VISIBLE,
  CONSTRAINT `fk_Airports_Countries1`
    FOREIGN KEY (`country_code`)
    REFERENCES `mydb`.`Countries` (`country_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airport`.`Terminals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airport`.`Terminals` (
  `terminal_id` INT NOT NULL AUTO_INCREMENT,
  `terminal_number` VARCHAR(10) NOT NULL,
  `airport_iata` CHAR(3) NOT NULL,
  PRIMARY KEY (`terminal_id`),
  INDEX `fk_table1_Airports1_idx` (`airport_iata` ASC) VISIBLE,
  CONSTRAINT `fk_table1_Airports1`
    FOREIGN KEY (`airport_iata`)
    REFERENCES `mydb`.`Airports` (`airport_iata`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airport`.`Gates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airport`.`Gates` (
  `gate_id` INT NOT NULL AUTO_INCREMENT,
  `gate_number` VARCHAR(10) NOT NULL,
  `terminal_id` INT NOT NULL,
  PRIMARY KEY (`gate_id`),
  INDEX `fk_Gates_table11_idx` (`terminal_id` ASC) VISIBLE,
  CONSTRAINT `fk_Gates_table11`
    FOREIGN KEY (`terminal_id`)
    REFERENCES `mydb`.`Terminals` (`terminal_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airport`.`Flights`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airport`.`Flights` (
  `flight_id` INT NOT NULL AUTO_INCREMENT,
  `flight_number` VARCHAR(20) NOT NULL,
  `departure_time` DATETIME NOT NULL,
  `arivival_time` DATETIME NOT NULL,
  `airplane_registration_number` VARCHAR(20) NOT NULL,
  `departure_airport` CHAR(3) NOT NULL,
  `destination_airport` CHAR(3) NOT NULL,
  `gate_id` INT NULL,
  PRIMARY KEY (`flight_id`),
  INDEX `fk_Flights_Airplanes1_idx` (`airplane_registration_number` ASC) VISIBLE,
  INDEX `fk_Flights_Airports1_idx` (`departure_airport` ASC) VISIBLE,
  INDEX `fk_Flights_Airports2_idx` (`destination_airport` ASC) VISIBLE,
  INDEX `fk_Flights_Gates1_idx` (`gate_id` ASC) VISIBLE,
  CONSTRAINT `fk_Flights_Airplanes1`
    FOREIGN KEY (`airplane_registration_number`)
    REFERENCES `mydb`.`Airplanes` (`airplane_registration_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Flights_Airports1`
    FOREIGN KEY (`departure_airport`)
    REFERENCES `mydb`.`Airports` (`airport_iata`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Flights_Airports2`
    FOREIGN KEY (`destination_airport`)
    REFERENCES `mydb`.`Airports` (`airport_iata`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Flights_Gates1`
    FOREIGN KEY (`gate_id`)
    REFERENCES `mydb`.`Gates` (`gate_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airport`.`PositionTypes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airport`.`PositionTypes` (
  `position_id` INT NOT NULL AUTO_INCREMENT,
  `position_type` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`position_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airport`.`Employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airport`.`Employees` (
  `employee_id` INT NOT NULL AUTO_INCREMENT,
  `employee_firstname` VARCHAR(25) NULL,
  `employee_lastname` VARCHAR(25) NULL,
  `position_id` INT NULL,
  PRIMARY KEY (`employee_id`),
  INDEX `fk_Employee_PositionType1_idx` (`position_id` ASC) VISIBLE,
  CONSTRAINT `fk_Employee_PositionType1`
    FOREIGN KEY (`position_id`)
    REFERENCES `mydb`.`PositionTypes` (`position_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airport`.`CheckIns`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airport`.`CheckIns` (
  `checkin_id` INT NOT NULL,
  `passenger_id` INT NOT NULL,
  `flight_id` INT NOT NULL,
  `seat_id` INT NULL,
  `employee_id` INT NULL,
  PRIMARY KEY (`checkin_id`),
  INDEX `fk_CheckIns_Passengers1_idx` (`passenger_id` ASC) VISIBLE,
  INDEX `fk_CheckIns_Flights1_idx` (`flight_id` ASC) VISIBLE,
  INDEX `fk_CheckIns_Seats1_idx` (`seat_id` ASC) VISIBLE,
  INDEX `fk_CheckIns_Employee1_idx` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `fk_CheckIns_Passengers1`
    FOREIGN KEY (`passenger_id`)
    REFERENCES `mydb`.`Passengers` (`passenger_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CheckIns_Flights1`
    FOREIGN KEY (`flight_id`)
    REFERENCES `mydb`.`Flights` (`flight_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CheckIns_Seats1`
    FOREIGN KEY (`seat_id`)
    REFERENCES `mydb`.`Seats` (`seat_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CheckIns_Employee1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `mydb`.`Employees` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airport`.`EmployeePasswords`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airport`.`EmployeePasswords` (
  `password_id` INT NOT NULL AUTO_INCREMENT,
  `employee_id` INT NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`password_id`),
  UNIQUE INDEX `employee_id_UNIQUE` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `employee_id`
    FOREIGN KEY (`employee_id`)
    REFERENCES `mydb`.`Employees` (`employee_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airport`.`BaggageStatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airport`.`BaggageStatus` (
  `baggage_status_id` INT NOT NULL AUTO_INCREMENT,
  `baggage_status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`baggage_status_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airport`.`BaggageTypes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airport`.`BaggageTypes` (
  `baggage_type_id` INT NOT NULL AUTO_INCREMENT,
  `baggage_type` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`baggage_type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airport`.`Baggages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airport`.`Baggages` (
  `baggage_id` INT NOT NULL AUTO_INCREMENT,
  `checkin_id` INT NOT NULL,
  `baggage_type_id` INT NOT NULL,
  `weight` DECIMAL NULL,
  `baggage_status_id` INT NULL,
  `paid` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`baggage_id`),
  INDEX `fk_Baggages_BaggageStatus1_idx` (`baggage_status_id` ASC) VISIBLE,
  INDEX `fk_Baggages_BaggageTypes1_idx` (`baggage_type_id` ASC) VISIBLE,
  INDEX `fk_Baggages_CheckIns1_idx` (`checkin_id` ASC) VISIBLE,
  CONSTRAINT `fk_Baggages_BaggageStatus1`
    FOREIGN KEY (`baggage_status_id`)
    REFERENCES `mydb`.`BaggageStatus` (`baggage_status_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Baggages_BaggageTypes1`
    FOREIGN KEY (`baggage_type_id`)
    REFERENCES `mydb`.`BaggageTypes` (`baggage_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Baggages_CheckIns1`
    FOREIGN KEY (`checkin_id`)
    REFERENCES `mydb`.`CheckIns` (`checkin_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airport`.`SeatsClassCount`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airport`.`SeatsClassCount` (
  `floor_id` INT NOT NULL COMMENT 'composite key\n',
  `seat_class_id` INT NOT NULL COMMENT 'composite key',
  `seat_count` INT NULL DEFAULT 0,
  `total_rows` INT NULL DEFAULT 0,
  `aisle_positions` VARCHAR(30) NOT NULL COMMENT 'coma seperated\n\n\"3,5\" - sled mqsto 3 i sled mqsto 5 ima aleq',
  PRIMARY KEY (`floor_id`, `seat_class_id`),
  INDEX `fk_SeatsClassCount_SeatsClass1_idx` (`seat_class_id` ASC) VISIBLE,
  CONSTRAINT `fk_SeatsClassCount_SeatsClass1`
    FOREIGN KEY (`seat_class_id`)
    REFERENCES `mydb`.`SeatsClass` (`seat_class_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SeatsClassCount_floors1`
    FOREIGN KEY (`floor_id`)
    REFERENCES `mydb`.`floors` (`floor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airport`.`BaggagePrices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `airport`.`BaggagePrices` (
  `baggage_type_id` INT NOT NULL,
  `company_iata` CHAR(2) NOT NULL,
  `airport_price` INT NOT NULL,
  `online_price` INT NOT NULL,
  `price_per_kg` INT NOT NULL,
  INDEX `fk_BaggagePrices_BaggageTypes1_idx` (`baggage_type_id` ASC) VISIBLE,
  INDEX `fk_BaggagePrices_AirplaneCompanies1_idx` (`company_iata` ASC) VISIBLE,
  CONSTRAINT `fk_BaggagePrices_BaggageTypes1`
    FOREIGN KEY (`baggage_type_id`)
    REFERENCES `mydb`.`BaggageTypes` (`baggage_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_BaggagePrices_AirplaneCompanies1`
    FOREIGN KEY (`company_iata`)
    REFERENCES `mydb`.`AirplaneCompanies` (`company_iata`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
